sudo: required
language: android

services:
  - docker

before_install:
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.android/build-cache
    - $HOME/build/kinecosystem/kin-sdk-android/google-cloud-sdk/
    - node_modules

env:
  - TEST_MATRIX=assemble
  - TEST_MATRIX=units
  - TEST_MATRIX=android_test_kin_sdk
  - TEST_MATRIX=android_test_backup_restore
  - TEST_MATRIX=android_test_backup_restore_ui

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26

script:
  - if [ $TEST_MATRIX == "assemble" ]; then ./scripts/ci_assemble.sh; fi
  - if [ $TEST_MATRIX == "units" ]; then ./scripts/ci_unit_test.sh; fi
  - if [ $TEST_MATRIX == "android_test_kin_sdk" ]; then ./scripts/ci_android_test_with_firebase.sh kin-sdk kin-sdk-sample kin-sdk-lib 2; fi
  - if [ $TEST_MATRIX == "android_test_backup_restore" ]; then ./scripts/ci_android_test_with_firebase.sh kin-backup-and-restore kin-backup-and-restore-sample kin-backup-and-restore-lib 0; fi
  - if [ $TEST_MATRIX == "android_test_backup_restore_ui" ]; then ./scripts/ci_android_test_with_firebase.sh kin-backup-and-restore kin-backup-and-restore-ui-tests kin-backup-and-restore-ui-tests 0; fi

after_success:
  - if [ $TEST_MATRIX != "assemble" ]; then bash <(curl -s https://codecov.io/bash); fi
